### ISSUE TITLE
Issue with package updates

### ISSUE THREAD

**Issue by davidbrochart** [conda-forge/jupyter_core-feedstock#57]
### Comment:

It's weird that no PR has been opened yet for [v5.1.0 and v4.12.0](https://pypi.org/project/jupyter-core/#history).

**Comment by ocefpaf** [comment]
We had some odd issues with the PyPI redirected URLs today. Maybe we should move this build to use GitHub source.

**Comment by bollwyvl** [comment]
there are now releases being created for the 5.x line, using in #58

the 4.x line was not _expected_ to get a PR (see elsewhere: `main` go up), but we can do a long-running branch: started, with new version on #59

**Comment by davidbrochart** [comment]
Thanks @bollwyvl !
